name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
  GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  ARBITRUM_ONE_RPC_URL: ${{ secrets.ARBITRUM_ONE_RPC_URL }}
  POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  GNOSIS_CHAIN_RPC_URL: ${{ secrets.GNOSIS_CHAIN_RPC_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo --version --verbose
      - run: cargo build --release --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: foundry-rs/foundry-toolchain@v1
      - run: cargo test --locked --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          command: fmt
          args: --all --check

      - name: cargo clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          args: --all --all-features -- -D warnings -W clippy::missing_docs_in_private_items
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: cargo doc
        uses: dtolnay/rust-toolchain@nightly
        env:
          RUSTDOCFLAGS: '-D missing_docs'
        with:
          command: doc
          args: --workspace --all-features --no-deps --document-private-items
